/**
 * Registro das rotas REST (api-rest.md §2–§5 e §8.1) — fonte do OpenAPI gerado
 * (`openapi.yaml`) e metadado para a API (onda 2) montar controllers/pipes.
 *
 * Fora deste registro por enquanto (entram com seus módulos): triagem (§6), reputação (§7),
 * moderação/operação (§8.2–§8.4).
 */
import { z } from 'zod';
import { CursorQuery, IdParams } from '../common.js';
import type { ErrorCode } from '../errors.js';
import {
  BidListResponse,
  BidParams,
  MyBidsQuery,
  SelectBidResponse,
  SubmitBidRequest,
  SubmitBidResponse,
  WithdrawBidResponse,
  BidView,
} from './bids.js';
import {
  BubbleDetail,
  BubbleSearchQuery,
  BubbleSearchResponse,
  CancelBubbleRequest,
  CategoryListResponse,
  CreateBubbleRequest,
  CreateImageUploadRequest,
  CreateImageUploadResponse,
  MyBubblesQuery,
  MyBubblesResponse,
  PublishBubbleRequest,
  ReportBubbleRequest,
  ReportCreatedResponse,
  UpdateBubbleRequest,
} from './bubbles.js';
import {
  CompanyVerificationResponse,
  ConfirmEmailRequest,
  ConsentHistoryResponse,
  DataExportResponse,
  DeletionRequest,
  DeletionScheduledResponse,
  ForgotPasswordRequest,
  GenericAcceptedResponse,
  GrantConsentRequest,
  LoginRequest,
  MeResponse,
  PayoutRecipientRequest,
  PayoutRecipientResponse,
  RegisterAcceptedResponse,
  RegisterRequest,
  ResendEmailRequest,
  ResetPasswordRequest,
  SessionResponse,
  UpdateMeRequest,
} from './identity.js';
import { NotificationsQuery, NotificationsResponse } from './notifications.js';
import {
  AcquireQuotaRequest,
  AcquireQuotaResponse,
  LeaveQuotaQuery,
  LeaveQuotaResponse,
  MyPaymentsResponse,
  MyPayoutsResponse,
  MyQuotasQuery,
  MyQuotasResponse,
  PaymentDetail,
} from './quotas.js';

export type HttpMethod = 'get' | 'post' | 'patch' | 'put' | 'delete';

/** Escopo de acesso (api-rest §1.2). */
export type RouteAuth =
  | 'public'
  | 'authenticated'
  | 'refresh-cookie'
  | 'pj'
  | 'pj-verified'
  | 'creator'
  | 'participant'
  | 'owner'
  | 'gateway';

export interface RouteResponse {
  description: string;
  /** Ausente = sem corpo (ex.: 204). */
  schema?: z.ZodType;
}

export interface RouteDef {
  operationId: string;
  method: HttpMethod;
  /** Caminho relativo a `/api/v1`, no estilo OpenAPI (`/bubbles/{id}`). */
  path: string;
  tag: 'identity' | 'bubbles' | 'quotas' | 'payments' | 'bids' | 'notifications' | 'webhooks';
  summary: string;
  auth: RouteAuth;
  /** `Idempotency-Key` (api-rest §1.3). */
  idempotency?: 'required' | 'recommended';
  /** Exige `If-Match` (concorrência otimista — api-rest §1.1). */
  ifMatch?: boolean;
  /** Exige `X-CSRF-Token` (rotas com cookie de refresh). */
  csrf?: boolean;
  params?: z.ZodObject;
  query?: z.ZodType;
  body?: z.ZodType;
  responses: Record<number, RouteResponse>;
  /** Códigos de erro documentados (catálogo `errors.ts`). */
  errors: readonly ErrorCode[];
}

const ok = (schema: z.ZodType, description = 'Sucesso'): RouteResponse => ({ schema, description });
const noContent: RouteResponse = { description: 'Sem conteúdo' };

const ON_WRITE = ['UNAUTHENTICATED', 'ACCOUNT_SUSPENDED', 'RATE_LIMITED'] as const;
const IDEMPOTENCY = [
  'IDEMPOTENCY_KEY_MISSING',
  'IDEMPOTENCY_KEY_REUSED',
  'IDEMPOTENCY_IN_PROGRESS',
] as const;

export const ROUTES = [
  // ---------------------------------------------------------------- identidade (F1, §2)
  {
    operationId: 'register',
    method: 'post',
    path: '/auth/register',
    tag: 'identity',
    summary: 'Cadastro PF ou PJ — resposta sempre genérica (anti-enumeração)',
    auth: 'public',
    body: RegisterRequest,
    responses: {
      202: ok(
        RegisterAcceptedResponse,
        'Sempre a mesma resposta, exista ou não conta com o e-mail/documento (SEC-08/SEC-22).',
      ),
    },
    errors: [
      'VALIDATION_FAILED',
      'CPF_INVALID',
      'CNPJ_INVALID',
      'CNPJ_NOT_ACTIVE',
      'CONSENT_REQUIRED',
      'CAPTCHA_REQUIRED',
      'RATE_LIMITED',
    ],
  },
  {
    operationId: 'confirmEmail',
    method: 'post',
    path: '/auth/email/confirm',
    tag: 'identity',
    summary: 'Confirmar e-mail e entrar',
    auth: 'public',
    body: ConfirmEmailRequest,
    responses: { 201: ok(SessionResponse, 'Sessão criada (+ cookie __Host-bv_rt)') },
    errors: ['VALIDATION_FAILED', 'TOKEN_EXPIRED', 'RATE_LIMITED'],
  },
  {
    operationId: 'resendConfirmationEmail',
    method: 'post',
    path: '/auth/email/resend',
    tag: 'identity',
    summary: 'Reenviar e-mail de confirmação — resposta sempre genérica',
    auth: 'public',
    body: ResendEmailRequest,
    responses: { 202: ok(GenericAcceptedResponse, 'Sempre a mesma resposta (anti-enumeração).') },
    errors: ['VALIDATION_FAILED', 'RATE_LIMITED'],
  },
  {
    operationId: 'login',
    method: 'post',
    path: '/auth/login',
    tag: 'identity',
    summary: 'Login com e-mail e senha',
    auth: 'public',
    body: LoginRequest,
    responses: { 200: ok(SessionResponse, 'Sessão criada (+ cookie de refresh)') },
    errors: [
      'VALIDATION_FAILED',
      'INVALID_CREDENTIALS',
      'CAPTCHA_REQUIRED',
      'ACCOUNT_SUSPENDED',
      'RATE_LIMITED',
    ],
  },
  {
    operationId: 'refreshSession',
    method: 'post',
    path: '/auth/refresh',
    tag: 'identity',
    summary: 'Renovar access token (rotação do refresh)',
    auth: 'refresh-cookie',
    csrf: true,
    responses: { 200: ok(SessionResponse) },
    errors: ['UNAUTHENTICATED', 'REFRESH_TOKEN_REUSED', 'RATE_LIMITED'],
  },
  {
    operationId: 'logout',
    method: 'post',
    path: '/auth/logout',
    tag: 'identity',
    summary: 'Encerrar sessão (revoga a família do refresh)',
    auth: 'refresh-cookie',
    csrf: true,
    responses: { 204: noContent },
    errors: ['UNAUTHENTICATED'],
  },
  {
    operationId: 'forgotPassword',
    method: 'post',
    path: '/auth/password/forgot',
    tag: 'identity',
    summary: 'Recuperação de senha — resposta sempre genérica',
    auth: 'public',
    body: ForgotPasswordRequest,
    responses: { 202: ok(GenericAcceptedResponse, 'Sempre a mesma resposta (anti-enumeração).') },
    errors: ['VALIDATION_FAILED', 'CAPTCHA_REQUIRED', 'RATE_LIMITED'],
  },
  {
    operationId: 'resetPassword',
    method: 'post',
    path: '/auth/password/reset',
    tag: 'identity',
    summary: 'Redefinir senha (revoga todas as sessões)',
    auth: 'public',
    body: ResetPasswordRequest,
    responses: { 204: noContent },
    errors: ['VALIDATION_FAILED', 'TOKEN_EXPIRED', 'RATE_LIMITED'],
  },
  {
    operationId: 'getMe',
    method: 'get',
    path: '/me',
    tag: 'identity',
    summary: 'Meus dados (mascarados)',
    auth: 'authenticated',
    responses: { 200: ok(MeResponse, 'Dados do titular (+ ETag)') },
    errors: ['UNAUTHENTICATED', 'TOKEN_EXPIRED'],
  },
  {
    operationId: 'updateMe',
    method: 'patch',
    path: '/me',
    tag: 'identity',
    summary: 'Atualizar meus dados',
    auth: 'authenticated',
    ifMatch: true,
    body: UpdateMeRequest,
    responses: { 200: ok(MeResponse) },
    errors: [
      ...ON_WRITE,
      'VALIDATION_FAILED',
      'VERSION_CONFLICT',
      'NICKNAME_UNAVAILABLE',
      'CPF_INVALID',
      'CNPJ_INVALID',
      'CNPJ_NOT_ACTIVE',
      'DOCUMENT_ALREADY_REGISTERED',
    ],
  },
  {
    operationId: 'requestCompanyVerification',
    method: 'post',
    path: '/me/company/verification',
    tag: 'identity',
    summary: 'Revalidar CNPJ agora',
    auth: 'pj',
    responses: { 202: ok(CompanyVerificationResponse) },
    errors: [...ON_WRITE, 'FORBIDDEN'],
  },
  {
    operationId: 'registerPayoutRecipient',
    method: 'post',
    path: '/me/payout-recipient',
    tag: 'identity',
    summary: 'Cadastro de recebedor (vendedor)',
    auth: 'authenticated',
    body: PayoutRecipientRequest,
    responses: { 202: ok(PayoutRecipientResponse) },
    errors: [...ON_WRITE, 'VALIDATION_FAILED'],
  },
  {
    operationId: 'getPayoutRecipient',
    method: 'get',
    path: '/me/payout-recipient',
    tag: 'identity',
    summary: 'Status do recebedor',
    auth: 'authenticated',
    responses: { 200: ok(PayoutRecipientResponse) },
    errors: ['UNAUTHENTICATED'],
  },
  {
    operationId: 'listConsents',
    method: 'get',
    path: '/me/consents',
    tag: 'identity',
    summary: 'Histórico versionado de consentimentos',
    auth: 'authenticated',
    responses: { 200: ok(ConsentHistoryResponse) },
    errors: ['UNAUTHENTICATED'],
  },
  {
    operationId: 'grantConsent',
    method: 'post',
    path: '/me/consents',
    tag: 'identity',
    summary: 'Conceder/revogar consentimento de marketing',
    auth: 'authenticated',
    body: GrantConsentRequest,
    responses: { 201: { description: 'Registrado' } },
    errors: [...ON_WRITE, 'VALIDATION_FAILED'],
  },
  {
    operationId: 'requestDataExport',
    method: 'post',
    path: '/me/data-exports',
    tag: 'identity',
    summary: 'Exportar meus dados (LGPD art. 18)',
    auth: 'authenticated',
    responses: { 202: ok(DataExportResponse) },
    errors: [...ON_WRITE, 'EXPORT_ALREADY_IN_PROGRESS'],
  },
  {
    operationId: 'getDataExport',
    method: 'get',
    path: '/me/data-exports/{id}',
    tag: 'identity',
    summary: 'Status/download da exportação',
    auth: 'owner',
    params: IdParams,
    responses: { 200: ok(DataExportResponse) },
    errors: ['UNAUTHENTICATED', 'NOT_FOUND'],
  },
  {
    operationId: 'requestAccountDeletion',
    method: 'post',
    path: '/me/deletion-request',
    tag: 'identity',
    summary: 'Excluir conta (agendada para +7 dias)',
    auth: 'authenticated',
    body: DeletionRequest,
    responses: { 202: ok(DeletionScheduledResponse) },
    errors: [
      ...ON_WRITE,
      'VALIDATION_FAILED',
      'INVALID_CREDENTIALS',
      'DELETION_BLOCKED_OBLIGATIONS',
    ],
  },
  {
    operationId: 'cancelAccountDeletion',
    method: 'delete',
    path: '/me/deletion-request',
    tag: 'identity',
    summary: 'Desistir da exclusão',
    auth: 'authenticated',
    responses: { 204: noContent },
    errors: ['UNAUTHENTICATED', 'NOT_FOUND'],
  },

  // ---------------------------------------------------------------- bolhas (F2–F4, §3)
  {
    operationId: 'listCategories',
    method: 'get',
    path: '/categories',
    tag: 'bubbles',
    summary: 'Categorias',
    auth: 'public',
    responses: { 200: ok(CategoryListResponse) },
    errors: ['RATE_LIMITED'],
  },
  {
    operationId: 'createBubble',
    method: 'post',
    path: '/bubbles',
    tag: 'bubbles',
    summary: 'Criar rascunho de bolha (venda ou compra)',
    auth: 'authenticated',
    idempotency: 'recommended',
    body: CreateBubbleRequest,
    responses: { 201: ok(BubbleDetail, 'Rascunho criado (status DRAFT, ETag "v1")') },
    errors: [
      ...ON_WRITE,
      'VALIDATION_FAILED',
      'INVALID_PRICE_TIERS',
      'INVALID_DURATION',
      'INVALID_QUOTA_RANGE',
      'INVALID_PJ_SHARE',
      'INVALID_SHIPPING_DAYS',
      'WRONG_BUBBLE_TYPE',
      'ACCOUNT_NOT_VERIFIED',
      'RECIPIENT_NOT_REGISTERED',
      'CONSENT_REQUIRED',
    ],
  },
  {
    operationId: 'searchBubbles',
    method: 'get',
    path: '/bubbles',
    tag: 'bubbles',
    summary: 'Canvas (viewport por bbox/zoom) ou lista acessível (view=list)',
    auth: 'public',
    query: BubbleSearchQuery,
    responses: { 200: ok(BubbleSearchResponse) },
    errors: ['VALIDATION_FAILED', 'RATE_LIMITED'],
  },
  {
    operationId: 'getBubble',
    method: 'get',
    path: '/bubbles/{id}',
    tag: 'bubbles',
    summary: 'Detalhe da bolha (com token inclui my_participation e allowed_actions)',
    auth: 'public',
    params: IdParams,
    responses: { 200: ok(BubbleDetail) },
    errors: ['BUBBLE_NOT_FOUND', 'RATE_LIMITED'],
  },
  {
    operationId: 'updateBubble',
    method: 'patch',
    path: '/bubbles/{id}',
    tag: 'bubbles',
    summary: 'Editar bolha (ACTIVE: só descrição e imagens)',
    auth: 'creator',
    ifMatch: true,
    params: IdParams,
    body: UpdateBubbleRequest,
    responses: { 200: ok(BubbleDetail) },
    errors: [
      ...ON_WRITE,
      'BUBBLE_NOT_FOUND',
      'FIELD_LOCKED_AFTER_PUBLISH',
      'VERSION_CONFLICT',
      'VALIDATION_FAILED',
      'INVALID_PRICE_TIERS',
      'INVALID_DURATION',
      'INVALID_QUOTA_RANGE',
      'INVALID_PJ_SHARE',
      'INVALID_SHIPPING_DAYS',
      'WRONG_BUBBLE_TYPE',
    ],
  },
  {
    operationId: 'publishBubble',
    method: 'post',
    path: '/bubbles/{id}/publish',
    tag: 'bubbles',
    summary: 'Publicar (DRAFT → ACTIVE); compra pré-autoriza a cota do criador',
    auth: 'creator',
    idempotency: 'required',
    params: IdParams,
    body: PublishBubbleRequest,
    responses: { 200: ok(BubbleDetail) },
    errors: [
      ...ON_WRITE,
      ...IDEMPOTENCY,
      'BUBBLE_NOT_FOUND',
      'BUBBLE_NOT_DRAFT',
      'INVALID_DURATION',
      'ACCOUNT_NOT_VERIFIED',
      'RECIPIENT_NOT_REGISTERED',
      'CREATOR_QUOTA_NOT_AUTHORIZED',
      'PAYMENT_METHOD_UNSUPPORTED',
      'PAYMENT_PROVIDER_UNAVAILABLE',
    ],
  },
  {
    operationId: 'cancelBubble',
    method: 'post',
    path: '/bubbles/{id}/cancel',
    tag: 'bubbles',
    summary: 'Cancelar bolha (rascunho ou ACTIVE sem cotas)',
    auth: 'creator',
    params: IdParams,
    body: CancelBubbleRequest,
    responses: { 200: ok(BubbleDetail) },
    errors: [...ON_WRITE, 'BUBBLE_NOT_FOUND', 'BUBBLE_HAS_QUOTAS', 'BUBBLE_NOT_ACTIVE'],
  },
  {
    operationId: 'listMyBubbles',
    method: 'get',
    path: '/me/bubbles',
    tag: 'bubbles',
    summary: 'Bolhas que criei',
    auth: 'authenticated',
    query: MyBubblesQuery,
    responses: { 200: ok(MyBubblesResponse) },
    errors: ['UNAUTHENTICATED', 'VALIDATION_FAILED'],
  },
  {
    operationId: 'reportBubble',
    method: 'post',
    path: '/bubbles/{id}/reports',
    tag: 'bubbles',
    summary: 'Denunciar bolha',
    auth: 'authenticated',
    idempotency: 'recommended',
    params: IdParams,
    body: ReportBubbleRequest,
    responses: { 201: ok(ReportCreatedResponse) },
    errors: [...ON_WRITE, 'BUBBLE_NOT_FOUND', 'REPORT_ALREADY_SUBMITTED', 'VALIDATION_FAILED'],
  },
  {
    operationId: 'createImageUpload',
    method: 'post',
    path: '/uploads/images',
    tag: 'bubbles',
    summary: 'URL assinada para upload de imagem/evidência',
    auth: 'authenticated',
    body: CreateImageUploadRequest,
    responses: { 201: ok(CreateImageUploadResponse) },
    errors: [...ON_WRITE, 'VALIDATION_FAILED'],
  },

  // ---------------------------------------------------------------- cotas e pagamento (F5, §4)
  {
    operationId: 'acquireQuota',
    method: 'post',
    path: '/bubbles/{id}/quotas',
    tag: 'quotas',
    summary: 'Entrar na bolha (cartão pré-autoriza; Pix reserva)',
    auth: 'authenticated',
    idempotency: 'required',
    params: IdParams,
    body: AcquireQuotaRequest,
    responses: { 201: ok(AcquireQuotaResponse) },
    errors: [
      ...ON_WRITE,
      ...IDEMPOTENCY,
      'VALIDATION_FAILED',
      'BUBBLE_NOT_FOUND',
      'BUBBLE_NOT_ACTIVE',
      'QUOTA_SOLD_OUT',
      'PIX_UNAVAILABLE_LATE',
      'PIX_TEMPORARILY_BLOCKED',
      'QUOTA_EXCEEDS_AVAILABLE',
      'PF_QUOTA_LIMIT',
      'PJ_SHARE_EXCEEDED',
      'CREATOR_CANNOT_JOIN',
      'ACCOUNT_NOT_VERIFIED',
      'PAYMENT_DECLINED',
      'PAYMENT_METHOD_UNSUPPORTED',
      'PAYMENT_PROVIDER_UNAVAILABLE',
      'CAPTCHA_REQUIRED',
    ],
  },
  {
    operationId: 'leaveQuota',
    method: 'delete',
    path: '/bubbles/{id}/quotas/me',
    tag: 'quotas',
    summary: 'Sair da bolha (fora da última hora)',
    auth: 'participant',
    params: IdParams,
    query: LeaveQuotaQuery,
    responses: { 200: ok(LeaveQuotaResponse) },
    errors: [...ON_WRITE, 'BUBBLE_NOT_ACTIVE', 'BUBBLE_EXIT_LOCKED', 'QUOTA_NOT_FOUND'],
  },
  {
    operationId: 'listMyQuotas',
    method: 'get',
    path: '/me/quotas',
    tag: 'quotas',
    summary: 'Minhas cotas',
    auth: 'authenticated',
    query: MyQuotasQuery,
    responses: { 200: ok(MyQuotasResponse) },
    errors: ['UNAUTHENTICATED', 'VALIDATION_FAILED'],
  },
  {
    operationId: 'getPayment',
    method: 'get',
    path: '/payments/{id}',
    tag: 'payments',
    summary: 'Detalhe do pagamento (linha do tempo)',
    auth: 'owner',
    params: IdParams,
    responses: { 200: ok(PaymentDetail) },
    errors: ['UNAUTHENTICATED', 'NOT_FOUND'],
  },
  {
    operationId: 'listMyPayments',
    method: 'get',
    path: '/me/payments',
    tag: 'payments',
    summary: 'Meus pagamentos',
    auth: 'authenticated',
    query: CursorQuery,
    responses: { 200: ok(MyPaymentsResponse) },
    errors: ['UNAUTHENTICATED', 'VALIDATION_FAILED'],
  },
  {
    operationId: 'listMyPayouts',
    method: 'get',
    path: '/me/payouts',
    tag: 'payments',
    summary: 'Repasses (vendedor)',
    auth: 'authenticated',
    responses: { 200: ok(MyPayoutsResponse) },
    errors: ['UNAUTHENTICATED'],
  },
  {
    operationId: 'pagarmeWebhook',
    method: 'post',
    path: '/webhooks/payments/pagarme',
    tag: 'webhooks',
    summary: 'Webhook do Pagar.me (corpo do gateway; processamento assíncrono com fetch-back)',
    auth: 'gateway',
    body: z.record(z.string(), z.unknown()),
    responses: { 200: { description: 'Evento persistido (ou duplicado)' } },
    errors: ['WEBHOOK_SIGNATURE_INVALID', 'RATE_LIMITED'],
  },

  // ---------------------------------------------------------------- lances (F8, §5)
  {
    operationId: 'listBids',
    method: 'get',
    path: '/bubbles/{id}/bids',
    tag: 'bids',
    summary: 'Lances da bolha de compra',
    auth: 'public',
    params: IdParams,
    responses: { 200: ok(BidListResponse) },
    errors: ['BUBBLE_NOT_FOUND', 'WRONG_BUBBLE_TYPE'],
  },
  {
    operationId: 'submitBid',
    method: 'post',
    path: '/bubbles/{id}/bids',
    tag: 'bids',
    summary: 'Enviar ou substituir lance (1 ativo por empresa)',
    auth: 'pj-verified',
    idempotency: 'required',
    params: IdParams,
    body: SubmitBidRequest,
    responses: { 201: ok(SubmitBidResponse) },
    errors: [
      ...ON_WRITE,
      ...IDEMPOTENCY,
      'VALIDATION_FAILED',
      'WRONG_BUBBLE_TYPE',
      'BUBBLE_NOT_ACTIVE',
      'BID_ABOVE_TARGET',
      'CREATOR_CANNOT_JOIN',
      'ACCOUNT_NOT_VERIFIED',
    ],
  },
  {
    operationId: 'withdrawBid',
    method: 'delete',
    path: '/bubbles/{id}/bids/{bidId}',
    tag: 'bids',
    summary: 'Retirar lance',
    auth: 'owner',
    params: BidParams,
    responses: { 200: ok(WithdrawBidResponse) },
    errors: [...ON_WRITE, 'BID_NOT_FOUND', 'BID_WITHDRAW_NOT_ALLOWED'],
  },
  {
    operationId: 'selectBid',
    method: 'post',
    path: '/bubbles/{id}/bids/{bidId}/select',
    tag: 'bids',
    summary: 'Escolher o lance vencedor (até 24 h após a explosão)',
    auth: 'creator',
    idempotency: 'required',
    params: BidParams,
    responses: { 200: ok(SelectBidResponse) },
    errors: [
      ...ON_WRITE,
      ...IDEMPOTENCY,
      'BID_SELECTION_NOT_OPEN',
      'BID_SELECTION_WINDOW_CLOSED',
      'BID_NOT_FOUND',
    ],
  },
  {
    operationId: 'listMyBids',
    method: 'get',
    path: '/me/bids',
    tag: 'bids',
    summary: 'Meus lances (PJ)',
    auth: 'pj',
    query: MyBidsQuery,
    responses: { 200: ok(z.object({ data: z.array(BidView) }).loose()) },
    errors: ['UNAUTHENTICATED', 'FORBIDDEN', 'VALIDATION_FAILED'],
  },

  // ---------------------------------------------------------------- notificações (F11, §8.1)
  {
    operationId: 'listNotifications',
    method: 'get',
    path: '/me/notifications',
    tag: 'notifications',
    summary: 'Minhas notificações',
    auth: 'authenticated',
    query: NotificationsQuery,
    responses: { 200: ok(NotificationsResponse) },
    errors: ['UNAUTHENTICATED', 'VALIDATION_FAILED'],
  },
  {
    operationId: 'markNotificationRead',
    method: 'post',
    path: '/me/notifications/{id}/read',
    tag: 'notifications',
    summary: 'Marcar notificação como lida',
    auth: 'owner',
    params: IdParams,
    responses: { 204: noContent },
    errors: ['UNAUTHENTICATED', 'NOT_FOUND'],
  },
  {
    operationId: 'markAllNotificationsRead',
    method: 'post',
    path: '/me/notifications/read-all',
    tag: 'notifications',
    summary: 'Marcar todas como lidas',
    auth: 'authenticated',
    responses: { 204: noContent },
    errors: ['UNAUTHENTICATED'],
  },
] as const satisfies readonly RouteDef[];

export type RouteId = (typeof ROUTES)[number]['operationId'];
